language: node_js
node_js:
- '6'
script:
- npm test
branches:
  only:
  - master
  - develop
env:
  global:
    secure: o2jSIRzoP5Sb0iJBFKTbo0Jom6/o04vJmTbmTCyOWbjU65WYiC4SyU6K02l53RCcqvb+6iTnW8Pe0e6zn1v54EoKvhoN2sYP3tI04G+/IXFkPb7nzHT3i7rA/tgxbde+cyp+PZIlO8tIdIHHZylxbgSGlMt5oZ5FAW4Mf2bG//iIAHM/dpS1oA8jKLDPtD8EccGtwn7q/qPl9jQXUE/ntncWWjg5Rxnf3el7wqnIB8aU2qQoQq5P9BVRoFyPdAU8V/Y2ShVrTd0uNIHbxaEi8e+b0wNhEoFVpJP38vPoCDj8BHnOGf3aDcQowyAPoX6CU9moMvq+50kHyoBCZH7D9c7DECUBmGUI4gpQMVyT6J90y4LuUMJeCCiL6pV6uf8+ApS9aLvPr6v9829ERpFZVNJvEtAF/p46DTAY/2nTkG/edLRj8kZvyLrxsMaQd2n71F0r2uC7IqvWgU0NNeD9g+mHg9Fu5lbkKYIikAjkQCaj7+6TCRDmhZjGoQJw8jN+BhmAp6Dd1hfYJYIlzPrlGCVLf1HzIcUm+rz78LOXw1Q8LAOhCuntf+IzigNGCNTvCJgIj8CzSfEFYYh3BeeMnDxzgnWoF5NK7ogLzEPVPx5mHb+Id3iAklZZIV/hwnKR+Bpau6J71k2YasdHSRjvqVbq2GSB1jBAgFQ4G5be6qI=
